[package]
name = "shed"
version = "0.1.0"
authors = ["ellis"]
edition = "2018"
documentation = "https://docs.rwest.io/shed"
repository = "https://hg.rwest.io/shed"
readme = "META"
license-file = "COPYING"
description = "~gardening tools~"
publish = ["crater"]

[dependencies]
# rlib
rlib = { version = "0.1.0", path = "../rlib", features = ["logger", "ctx", "cli", "obj", "flate", "db", "net", "hg"] }
tenex = { version = "0.1.0", path = "../tenex", features = ["ipapi"] }

# contrib
libc = "0.2"
serde = { version = "1.0.128", features = ["derive"] }
clap = "3.0.0-beta.4"
crossterm = { version = "0.17", features = ["event-stream"] }
cursive = { version = "0.16" }
rustpython-vm = { version = "0.1.2", git = "https://github.com/RustPython/RustPython", features = ["ssl-vendor", "freeze-stdlib", "jit"] }
rustpython-parser = { version = "0.1.2", git = "https://github.com/RustPython/RustPython"}
rustyline-derive = { version = "0.5" }
rustyline = { version = "9.0.0" }
num-traits = "0.2"
cfg-if = "1.0"