[package]
name = "shed"
version = "0.1.0"
authors = ["ellis"]
edition = "2018"
documentation = "https://docs.rwest.io/shed"
repository = "https://hg.rwest.io/shed"
readme = "META"
license-file = "COPYING"
description = "~gardening tools~"
publish = ["crater"]

[dependencies]
# rlib
logger = { version = "0.1.0", path = "../rlib/logger" }
ctx = { version = "0.1.0", path = "../rlib/ctx" }
util = { version = "0.1.0", path = "../rlib/util", features = ["cli"] }
cfg = { version = "0.1.0", path = "../rlib/cfg" }
obj = { version = "0.1.0", path = "../rlib/obj" }
flate = { version = "0.1.0", path = "../rlib/flate" }
db = { version = "0.1.0", path = "../rlib/db" }
net = { version = "0.1.0", path = "../rlib/net", features = ["server", "client"] }
# contrib
serde = { version = "1.0.128", features = ["derive"] }
[dev-dependencies]
tempfile = { version = "3.2.0" }