[package]
name = "shedctl"
version = "0.1.0"
authors = ["ellis"]
edition = "2018"
documentation = "https://docs.rwest.io/shed"
repository = "https://hg.rwest.io/shed"
readme = "META"
license-file = "COPYING"
description = "~gardening tools~"
publish = ["crater"]

[[bin]]
name = "shed"
path = "src/main.rs"

[dependencies]
logger = { version = "0.1.0", path = "../rlib/logger" }
shed = { version = "0.1.0", path = "lib" }
ctx = { version = "0.1.0", path = "../rlib/ctx" }
clap = { version = "3.0.0-beta.2", path = "../contrib/rust/clap" }

[env]
SHED_CFG = "$HOME/.config/shed.ron"
SHED_SRC = "$HOME/src"
SHED_BIN = "$HOME/.cargo/bin/shedctl"